[SourceHanSansPlus-Regular]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF+
	s=3,1,0x411,Regular
	f=Source Han Sans+
	s=Regular

[SourceHanSansPlus-Bold]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF+
	s=3,1,0x411,Bold
	f=Source Han Sans+
	s=Bold

[SourceHanSansPlusK-Regular]
	f=3,1,0x412,\BCF8\ACE0\B515+
	s=3,1,0x412,Regular
	f=Source Han Sans+ K
	s=Regular

[SourceHanSansPlusK-Bold]
	f=3,1,0x412,\BCF8\ACE0\B515+
	s=3,1,0x412,Bold
	f=Source Han Sans+ K
	s=Bold

[SourceHanSansPlusSC-Regular]
	f=3,1,0x804,\601D\6E90\9ED1\4F53+
	s=3,1,0x804,Regular
	f=Source Han Sans+ SC
	s=Regular

[SourceHanSansPlusSC-Bold]
	f=3,1,0x804,\601D\6E90\9ED1\4F53+
	s=3,1,0x804,Bold
	f=Source Han Sans+ SC
	s=Bold

[SourceHanSansPlusTC-Regular]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4+
	s=3,1,0x404,Regular
	f=Source Han Sans+ TC
	s=Regular

[SourceHanSansPlusTC-Bold]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4+
	s=3,1,0x404,Bold
	f=Source Han Sans+ TC
	s=Bold
